name: Mirror to personal repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repo de l'école (historique complet)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push vers le repo miroir personnel
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          git remote add mirror "https://x-access-token:${MIRROR_TOKEN}@github.com/VOTRE_USER/VOTRE_REPO_MIROIR.git"
          git push mirror HEAD:main --force
